#ifndef COMMUNICATION_COMMANDS
#define COMMUNICATION_COMMANDS

enum SESSION_COMMANDS {
    START,
    STOP,
    STATUS,
    PARAMETERS
};

#define READ_COMMAND 'r'
#define WRITE_COMMAND 'w'
#define EXECUTE_COMMAND 'x'


#endif